### ISSUE TITLE
time to register package?

### ISSUE THREAD

**Issue by fogg-uw** [cecileane/PhyloCoalSimulations.jl#6]
i'm hitting some bugs in my simulation code that would probably go away if PhyloCoalSimulations were a package that i had installed the normal way instead of calling on my local machine.  are we ready to release v0.1.0 to the masses?

**Comment by cecileane** [comment]
let's do it. It's a matter of tagging JuliaRegistrator in a comment. Check that on the latest commit, in a minute.

**Comment by cecileane** [comment]
please follow the comments on this commit 8bd5c503ddea3ac5f53fa63d3eee24b3e59a98b6 . Don't comment manually, otherwise it will block the automatic process.

**Comment by cecileane** [comment]
done! 🎉
